package cli

import "fmt"

func PrintHelp() {
	fmt.Println("Mongo Easy")
	fmt.Println()
	fmt.Println("Import MongoDB datasets from JSON, JSONL, CSV, or ZIP files.")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  mongo-easy import <dataset> [options]")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  --mode <mode>")
	fmt.Println("      ask       Ask before importing into existing collections")
	fmt.Println("      append    Add documents to the collection")
	fmt.Println("      replace   Replace existing collection data")
	fmt.Println("      upsert    Update existing documents or insert new ones")
	fmt.Println()
	fmt.Println("  --key <field>")
	fmt.Println("      Specify the field to use as the upsert key")
	fmt.Println()
	fmt.Println("  --database <name>, -db <name>")
	fmt.Println("      Select the MongoDB database to use")
	fmt.Println("      Default: mongo-easy")
	fmt.Println()
	fmt.Println("  --collection-mode <mode>")
	fmt.Println("      ask       Ask when multiple files target the same collection")
	fmt.Println("      combine   Combine multiple files into one collection")
	fmt.Println("      separate  Create separate collections")
	fmt.Println("      cancel    Skip the conflicting collection")
	fmt.Println()
	fmt.Println("Supported formats:")
	fmt.Println("  .json")
	fmt.Println("  .jsonl")
	fmt.Println("  .csv")
	fmt.Println("  .zip")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  mongo-easy import data.json --mode replace")
	fmt.Println("  mongo-easy import data.csv --mode append")
	fmt.Println("  mongo-easy import data.zip --mode upsert")
	fmt.Println("  mongo-easy import data.zip --mode replace --collection-mode separate")
	fmt.Println("  mongo-easy import data.json --mode upsert --key customer_id")
	fmt.Println("  mongo-easy import data.json --database analytics --mode replace")
}
